apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: deployapp
  labels:
    app.kubernetes.io/name: deployapp
    app.kubernetes.io/part-of: deployapp-project
    kubernetes.azure.com/generator: devhub
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: deployapp