apiVersion: v1
kind: Service
metadata:
  name: deployapp
  namespace: dev
  labels:
    app.kubernetes.io/name: deployapp
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: deployapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080